### ISSUE TITLE
Send_msg KeyError

### ISSUE THREAD

**Issue by luiscazares** [bcicen/slacksocket#14]
I know it just got uploaded two second ago,  but wanted to let you know when trying to .send_msg I'm getting a key error on line 123 of client.py 
msg.ts = e.event['ts']

**Comment by luiscazares** [comment]
I #'ed it out and the msg sent. doesn't give me a timestamp but at least it's not returning an error

**Comment by bcicen** [comment]
Thanks @theguyoncouch; I can't seem to replicate the error -- can you post the error message here?

**Comment by luiscazares** [comment]
> > > sc.send_msg('hello', '#connect4')
> > > Traceback (most recent call last):
> > >     File "<stdin>", line 1, in <module>
> > >     File "/usr/local/lib/python3.4/dist-packages/slacksocket/client.py",
> > > line 123, in send_msg
> > >         msg.ts = e.event['ts']
> > > KeyError: 'ts'

**Comment by bcicen** [comment]
I've pushed https://github.com/bcicen/slacksocket/commit/54620e51c2637ba140b719d4878627049f280f8f to correct this. Thanks again for your feedback.
