### ISSUE TITLE
daemonize client

### ISSUE THREAD

**Issue by keypulse** [bcicen/slacksocket#18]
Issue: Threading - KB interrupt during threaded event handling will kill event thread but is unbound to main event thread.

Desc: The main thread needs to be daemonized to be aware of it's children during locks to have effective threading (and exception handling).

Please add:
self.thread.daemon = True
between lines 81 and 82 in client.py:
https://github.com/bcicen/slacksocket/blob/master/slacksocket/client.py

```
    self._thread = Thread(target=self._open)
    self._thread.daemon = True
    self._thread.start()
```

Thank you! :)

**Comment by bcicen** [comment]
Great catch @keypulse; thanks! Added in https://github.com/bcicen/slacksocket/commit/eb33c40297041a8a6f92b0a9fd1baae96650e633 and available in pip release 0.6.1.
