### ISSUE TITLE
migration_in_progress error event

### ISSUE THREAD

**Issue by actioncrypto** [bcicen/slacksocket#19]
There appears to be no way to currently handle this event in the stream, and will break a connection.

line 42 of `client.py` will return this very sparsely and break the code when it occurs:

```
SlackSocketAPIError: Error from slack api:
 {"ok":false,"error":"migration_in_progress"}
```

perhaps we can add in a try/catch time delay retry?  Please advise.

**Comment by bcicen** [comment]
Thanks for pointing this out @actioncrypto.

A try clause checking the error message from Slack and retrying the request after a delay sounds like the best direction. Any idea what a reasonable timeout for this action would be(and how long connection state stays in the migrating state)?

**Comment by actioncrypto** [comment]
No problem @bcicen!

Yes, a try/catch sounds like it would work, and I can't imagine it is more than a few seconds to delay before retrying. Maybe try 1 second delay & retry? or linear back-off?

```
s = SlackSocket(API_KEY)
for event in s.events():
    pass <-- happens somewhere in here
```

And the error quoted above references that line 42 as the spot to look.

**Comment by bcicen** [comment]
Sounds good; I've added a sleep/retry to the slackclient in https://github.com/bcicen/slacksocket/commit/750a617c87bf8ef74b232481efc70bdc376a48c1. I'll include this in a hotfix release to pypi as well. Thanks again for your feedback!
