### ISSUE TITLE
No human readable userIDs or ChannelIDs?

### ISSUE THREAD

**Issue by ni1by2** [bcicen/slacksocket#20]
I'm a beginner python developer, and this library is an awesome resource both for my learning as well as for a project i had in mind, so thanks! my issue is that I've set Translate = True, when calling SlackSocket, however I'm still not getting the human readable ids: My code is as follows:

```
import slacksocket

flow = slacksocket.Slacksocket('my-slack-token',translate=True,event_filters=['message'])

for events in flow.events():
   with open('slacklog', 'a') as log:
       log.write('\n')
       log.write(event.json)
```

but the slacklog file still shows the non-translated channel and user IDS, viz.

```
{"type":"message","channel":"C0FUABZMF","user":"U0FU80W0K","text":"testing messages with event filters on","ts":"1449320459.000022","team":"T0FU5BBA8"}
```

any idea what i'm missing?

**Comment by luiscazares** [comment]
Hey there, 
So two things. I believe translate is default true now. at least that's how i read his client.py so you shouldn't have to worry about adding it. Also did you rewrite this here or copy paste? You have for events in flow.events() but then have event.json without the s. either wait try "event.event" that should give you the translated user and channel.

as in:

flow = slacksocket.SlackSocket('my-slack-token',translate=True,event_filters=['message'])

for event in flow.events():
   with open('slacklog', 'a') as log:
       log.write('\n')
       log.write(event.event)

**Comment by bcicen** [comment]
True, the translated channel/user IDs are only found in the SlackEvent 'event' dictionary, while the 'json' attribute doesn't get updated -- perhaps this should be updated so translated IDs appear in both?

**Comment by ni1by2** [comment]
Ahh excellent, the event.event dictionary object is exactly what I was looking for! Many thanks.

**Comment by bcicen** [comment]
I've updated slackevent.json to return the same translated values as the event dictionary in #21
