### ISSUE TITLE
[Enhancement]: Make SlackSocket a context

### ISSUE THREAD

**Issue by brianbruggeman** [bcicen/slacksocket#24]
Currently `SlackSocket` can only be used as defined within the top level examples.  Providing `SlackSocket` as a context would enhance usability.  This is a common use-case for any type of stream or pipe or socket.

New Use case:

```
with SlackSocket(token) as socket:
    if not socket.send_msg(msg, channel_name).sent:
        print('Error message not sent: "{msg}"', file=sys.stderr)
```

Additions:

```
def __enter__(self):
    # web socket connection logic here
    return self

def __exit__(self, exc_type, exc_value, exc_traceback):
    # handle web socket disconnection here
```

**Comment by bcicen** [comment]
Good point. With your use case, the overhead of initializing a new websocket on every message send/receive could be a bit much as a few things happen every time SlackSocket is initialzed:
- auth test is performed
- new websocket url/token is requested from Slack
- websocket connection is setup and message handlers attached
- channel and user lists are pulled to provide ID to human-readable name translation

I'll leave this open for now; if others are interested in this kind of functionality perhaps a "quick init" option can be added.

**Comment by bcicen** [comment]
added simple context support in #30
