### ISSUE TITLE
is this support multiple token for bot-user?

### ISSUE THREAD

**Issue by erwinyusrizal** [bcicen/slacksocket#29]
Hi @bcicen is this support multiple token for bot-user ?

**Comment by bcicen** [comment]
Hi @erwinyusrizal. You can only use one token per SlackSocket instance; however, creating multiple SlackSocket objects for each account shouldn't be an issue.

**Comment by erwinyusrizal** [comment]
@bcicen yes i got it working now, the problem is now after oauth, I call this

```
client = SlackSocket(token)
for event in client.events():
    print(event.json)
```

any method from the `client` object that I can use to do next request?

**Comment by bcicen** [comment]
The [get_event](http://slacksocket.readthedocs.org/en/latest/client/#get_event) method will return the next single event matching providing filters; however, it is blocking.

Perhaps we can add a `block=False` arg to this and simply return `None` when no events have been received.

**Comment by erwinyusrizal** [comment]
the problem is after oauth process i cannot update the RTM to listen/connect the new `bot_access_token` since it is already started listening.  I think for bot-user app the flow is not that simple. I think I need to run that in the background, any idea?

**Comment by bcicen** [comment]
Have you tried using multiple SlackSocket objects? e.g

``` python
client1 = SlackSocket(token1)
client2 = SlackSocket(token2)
```

**Comment by bcicen** [comment]
closing this for now; do let me know if you continue to have trouble.
