### ISSUE TITLE
Improve potential silent infinite loop

### ISSUE THREAD

**Issue by andrew-boutin** [bcicen/slacksocket#36]
Recently ran into an infinite loop here: https://github.com/vektorlab/slacksocket/blob/9dfb462471e1634feb7c6dea9d53d490c8b31fd0/slacksocket/client.py#L63-L65

There's no way to set a timeout value and there is no logging to indicate what is happening. Can some logging be added and/or a configurable timeout? The default could be no timeout so the existing functionality doesn't change.

Thank you.

**Comment by Karin-Basis** [comment]
+1

I'm getting stuck in this infinite loop and not sure what's going on.

**Comment by andrew-boutin** [comment]
@Karin-Basis as a workaround try forcing `websocket-client>=0.35.0,<=0.48.0`.

**Comment by bcicen** [comment]
[internal connection state tracking](https://github.com/vektorlab/slacksocket/blob/master/slacksocket/client.py#L69) and timeout handling has been added as of v1.0 to resolve
