### ISSUE TITLE
Dependency update breaks functionality change version pin

### ISSUE THREAD

**Issue by andrew-boutin** [bcicen/slacksocket#37]
[`requirements.txt`](https://github.com/vektorlab/slacksocket/blob/9dfb462471e1634feb7c6dea9d53d490c8b31fd0/requirements.txt#L2) has `websocket-client>=0.35.0`. It looks like version `0.49.0` breaks functionality. Using version `0.48.0` works though.

Can this dependency get changed to `websocket-client>=0.35.0,<=0.48.0` at least until either `websocket-client` fixes backwards compatibility or this library is updated to handle the changes?

**Comment by bcicen** [comment]
fixed in #38
