### ISSUE TITLE
Reraise KeyboardInterrupt

### ISSUE THREAD

**Issue by GregHilston** [bcicen/slacksocket#39]
I'm using slacksocket to write another library. 

I'm having a very difficult time gracefully shutting my application down when a user types in `CTRL + C` when my app is blocked on slacksocket's `events` method and the `KeyboardInterrupt` is caught and not re raised.

**Comment by bcicen** [comment]
Improved signal handling/shutdown has been [added](https://github.com/vektorlab/slacksocket/commit/931fcf328fe315c8696c4fea0f75af502e1e43d8) in v0.9.2, now published on pypi

**Comment by GregHilston** [comment]
Much thanks! @bcicen
